version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  cache:
    image: "redis:latest"
    expose:
      - 6379

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres_password
      - PGPORT=5432
      - REDIS_HOST=cache
      - REDIS_PORT=6379
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
